# This file is used to define the data models for the invite code feature.
# A code is generated by a manager and sent to a new manager who wants to register.
# The new manager uses the code to register and the code is marked as used.

from datetime import datetime, timezone
from pydantic import BaseModel, ConfigDict, EmailStr, Field
from app.models.py_object_id import PyObjectId

# body of POST /admin/invite-code. It is used to validate the request body and ensure that the required fields are present and valid.
class InviteCodeCreate(BaseModel):
    target_email: EmailStr

# Describes the shape of the invite code data stored in the database.
# It includes the code, the target email, the id of the manager who created the code, and timestamps for when the code was created and used.
class InviteCodeInDB(BaseModel):
    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    id: PyObjectId = Field(alias="_id")
    code: str
    target_email: EmailStr
    created_by: PyObjectId
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    used_by: PyObjectId | None = None
    used_at: datetime | None = None

# Same as InviteCodeInDB but without the used_by and used_at fields. It is used to return the invite code data to the client when a new invite code is created.
class InviteCodeOut(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: PyObjectId = Field(alias="_id")
    code: str
    target_email: EmailStr
    created_by: PyObjectId
    created_at: datetime
    used_by: PyObjectId | None = None
    used_at: datetime | None = None